services:
  wryon_wg_client:
    build:
      context: .
      dockerfile: ./docker/wg_client/Dockerfile
    container_name: wryon_wg_client
    image: wryon_wg_client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./docker/wg_client/config:/config
    networks:
      - wryon
    restart: unless-stopped

  wryon_ssh_server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: wryon_ssh_server
    network_mode: "service:wryon_wg_client"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PUBLIC_KEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOKzI211EV0uPFyCqFz/OA4V4QLUYJPp8ufO4yHvnodC # phone-1 termux
      - PUBLIC_KEY_URL=https://github.com/ramity.keys
      - SUDO_ACCESS=true
      - PASSWORD_ACCESS=false
      - USER_NAME=ramity
    volumes:
      - ./docker/ssh_server/config:/config
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

networks:
  wryon:
    name: wryon
    driver: bridge
