services:
  wryon_wireguard_server:
    build:
      context: .
      dockerfile: ./docker/wireguard_server/Dockerfile
    container_name: wryon_wireguard_server
    image: wryon_wireguard_server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      # Development:
      - SERVERURL=192.168.1.3
      # - SERVERURL=wryon_wireguard_server
      # Production:
      # - SERVERURL=vpn.domain.com
      - SERVERPORT=51820
      # - INTERNAL_SUBNET=10.13.13.0
      # Number of client configs to generate (or a list of names)
      - PEERS=2
      - PEERDNS=auto
      - CONFIG_PATH=/config
      - ALLOWEDIPS=10.13.13.0/24
    volumes:
      - ./docker/wireguard_server/config:/config
      - /lib/modules:/lib/modules:ro
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped
    networks:
      - wryon

  wryon_bob:
    image: nginx:alpine
    container_name: wryon_bob
    network_mode: "service:wryon_wireguard_server"
    depends_on:
      - wryon_wireguard_server

  wryon_wireguard_client:
    build:
      context: .
      dockerfile: ./docker/wireguard_client/Dockerfile
    container_name: wryon_wireguard_client
    image: wryon_wireguard_client
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    depends_on:
      - wryon_wireguard_server
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ./docker/wireguard_client/config:/config
    networks:
      - wryon

  wryon_alice:
    image: alpine
    container_name: wryon_alice
    network_mode: "service:wryon_wireguard_client"
    depends_on:
      - wryon_wireguard_client
    command: /bin/sh -c "apk add curl && sleep infinity"

  # wryon_cnc:
  #   build:
  #     context: .
  #     dockerfile: ./docker/cnc/Dockerfile
  #   container_name: wryon_cnc
  #   depends_on:
  #     - wryon_wireguard_client
  #   network_mode: service:wryon_wireguard_client
  #   image: wryon_cnc
  #   restart: unless-stopped

networks:
  wryon:
    driver: bridge
